Fix Toaster NPE
2021-10-17 20:30:06.410 26911-26911/com.example.lmt E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.lmt, PID: 26911
    java.lang.RuntimeException: Unable to create service com.example.lmt.TouchService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3966)
        at android.app.ActivityThread.access$1500(ActivityThread.java:220)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1876)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7398)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
        at com.example.lmt.Toaster.<init>(Toaster.java:23)
        at com.example.lmt.Toaster.getInstance(Toaster.java:32)
        at com.example.lmt.TouchService.onCreate(TouchService.java:93)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3954)
        at android.app.ActivityThread.access$1500(ActivityThread.java:220) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1876) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7398) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940) 